lexik_jwt_authentication:
    secret_key: '%env(resolve:JWT_SECRET_KEY)%'
    public_key: '%env(resolve:JWT_PUBLIC_KEY)%'
    pass_phrase: '%env(JWT_PASSPHRASE)%'
    token_ttl: 36000
    api_platform:
        check_path: /api/login_check
        username_path: email
        password_path: security.credentials.password
    token_extractors:
        authorization_header:
            enabled: true
            prefix: JWT  
            name: Authorization
